# Generated by cpp11: do not edit by hand

cpp_rgb_to_hsluv <- function(rgb) {
  .Call(`_hsluv_cpp_rgb_to_hsluv`, rgb)
}

cpp_hsluv_to_rgb <- function(hsluv) {
  .Call(`_hsluv_cpp_hsluv_to_rgb`, hsluv)
}

cpp_hex_to_rgb <- function(hex) {
  .Call(`_hsluv_cpp_hex_to_rgb`, hex)
}

cpp_rgb_to_hex <- function(rgb) {
  .Call(`_hsluv_cpp_rgb_to_hex`, rgb)
}
